### ISSUE TITLE
Ballerina application fails when we use `zipkin` module with `Update 9` versions

### ISSUE THREAD

**Issue by NipunaMadhushan** [ballerina-platform/module-ballerinax-zipkin#14]
**Description:**
Application fails with the following error when we use `zipkin` module with  Ballerina `Update 9` versions.

```
[2024-07-25 09:57:24,792] SEVERE {b7a.log.crash} - 'io.opentelemetry.api.metrics.LongValueObserverBuilder io.opentelemetry.api.metrics.Meter.longValueObserverBuilder(java.lang.String)' 
java.lang.NoSuchMethodError: 'io.opentelemetry.api.metrics.LongValueObserverBuilder io.opentelemetry.api.metrics.Meter.longValueObserverBuilder(java.lang.String)'
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.<init>(BatchSpanProcessor.java:148)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.<init>(BatchSpanProcessor.java:116)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor.<init>(BatchSpanProcessor.java:69)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessorBuilder.build(BatchSpanProcessorBuilder.java:140)
        at io.ballerina.observe.trace.zipkin.ZipkinTracerProvider.initializeConfigurations(ZipkinTracerProvider.java:83)
        at ballerinax.zipkin.0.tracer_provider.externInitializeConfigurations(tracer_provider.bal:48)
        at ballerinax.zipkin.0.tracer_provider.init(tracer_provider.bal:43)
        at ballerinax.zipkin.0.$_init.$gen$&0046&0060init&0062(zipkin:1)
        at nipunal.zipkin_test.0.$_init.$moduleInit(zipkin_test)
        at nipunal.zipkin_test.0.$_init.$moduleExecute(zipkin_test)
        at nipunal.zipkin_test.0.$_init.$lambda$$moduleExecute$(zipkin_test)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:320)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:287)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**

**Steps to reproduce:**

**Related Issues:**

**Comment by NipunaMadhushan** [comment]
This occurs due to the `opentelemetry` dependency version update in Ballerina `Update 9` versions.
